name: tests

on: push

jobs:
  test:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    env:
      COVERAGE_RUBY_VERSION: 2.6
      BUNDLE_PATH: vendor/bundle
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - jruby
          - truffleruby
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: ruby-${{ matrix.ruby }}-gems-${{ hashFiles('config.gemspec', 'gemfiles/**') }}
          restore-keys: |
            ruby-${{ matrix.ruby }}-gems-

      - name: Prepare environment
        run: |
          sudo apt-get -y install libsqlite3-dev libxslt1-dev

      - name: Install
        run: |
          bundle install
          bundle exec appraisal install

      - name: Test
        run: bundle exec appraisal rspec

      - name: Publish code coverage
        if: startsWith(env.RUBY_VERSION, env.COVERAGE_RUBY_VERSION)
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bundle exec appraisal rspec
